Content:
  
  Contact:
    Contact:
      page:  true
      components:
        list:
        show:

  "Contact Data":

    PhoneNumber:
      components:
        list:
        show:

    Address:
      components:
        list:
        show:

    Email:
      components:
        list:
        show: