<?php

/**
 * PluginPhoneNumberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPhoneNumberTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPhoneNumberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPhoneNumber');
    }
}