<?php

/**
 * PluginEmailTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEmailTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEmailTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEmail');
    }
}