<?php

/**
 * PluginCompanyContactRelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCompanyContactRelTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCompanyContactRelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCompanyContactRel');
    }
}