<?php

/**
 * PluginAddressTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginAddressTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginAddressTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginAddress');
    }
}