<?php

/**
 * PluginContactTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginContactTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginContactTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginContact');
    }
}